version: '3'

services:
  tg-bot:
    container_name: 'tg-bot'
    build:
      context: ./tg-bot/

  web:
    container_name: 'django'
    env_file:
      - .env
    build:
      context: ./django/
    ports:
      - "5000:5000"
    command:
      - '/bin/sh'
      - '-c'
      - '/bin/sleep 10 && python manage.py migrate && python manage.py runserver 0.0.0.0:5000'
    depends_on:
      - mysql_db

  mysql_db:
    container_name: mysql_db
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - '3306:3306'
    env_file:
      - .env

  redis:
    container_name: 'redis'
    image: redis
    restart: always

  worker:
    container_name: 'worker'
    build:
      context: ./django/
    restart: always
    env_file:
      - .env
    volumes:
      - ./docker_media:/main_app/media
    command: ['celery', '-A', 'voxweb', 'worker', '--uid', '0']
