# Generated by Django 4.2.3 on 2023-07-28 21:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='products_pictures/', verbose_name='изображение товара')),
                ('alt', models.TextField(verbose_name='описание изображения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'фотография товара',
                'verbose_name_plural': 'фотографии товаров',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.CharField(max_length=500, null=True, verbose_name='ссылка')),
                ('title', models.CharField(max_length=500, verbose_name='название')),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена со скидкой')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена без скидки')),
                ('sale', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='скидка')),
                ('count_in_stock', models.CharField(max_length=100, null=True, verbose_name='количество в наличии')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='рейтинг')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('image', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.productimage', verbose_name='изображение товара')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
    ]
